### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by lashagosh** [ABGEO/nomrebi-com#1]
I'm getting 0 records as a response. After investigation, the raw response from the API is the following: `{"res":"no","err":"#017"}`. I'm wondering is this the API issue? Do we need to update something in the code?

**Comment by ABGEO** [comment]
@LGosh I guess they added some kind of authentication protocol to the API, so we can't do anything with it.

**Comment by ABGEO** [comment]
Hey @LGosh,

This issue is fixed in [this](https://github.com/ABGEO/nomrebi-py/releases/tag/v1.2.0) release.

**Comment by lashagosh** [comment]
Thanks, it works fine now.

**Comment by lashagosh** [comment]
API is broken again, it returns empty array as a response for all numbers.
